create database AnBinh

CREATE TABLE NHANVIEN (
	MANV INT,
	HOTEN NVARCHAR(20),
	NGAYSINH DATE,
	CMND CHAR(15),
	SDT CHAR(10),
	EMAIL VARCHAR(25),
	DIACHI NVARCHAR(50),
	VITRI NVARCHAR(20),
	LUONG FLOAT,
	VAITRO NVARCHAR(20),
	PRIMARY KEY (MANV)
);

CREATE TABLE TRUNGTAM (
	STT INT,
	DIACHI NVARCHAR(50),
	NGAYBATDAU DATE,
	PRIMARY KEY (STT)
);

CREATE TABLE BANGCAP(
	MANV INT,
	MABANCAP INT,
	TENBANG NVARCHAR(20),
	NOICAP NVARCHAR(20),
	CAPBAC NVARCHAR(20),
	LINHVUC NVARCHAR(20)
);

CREATE TABLE LICHCATRUC(
	MANV INT,
	NGAY DATE,
	BUOI NVARCHAR(6),
);
