DROP DATABASE AnBinh
create database AnBinh
USE AnBinh
--NHANVIEN
CREATE TABLE NHANVIEN (
	MANV INT,
	HOTEN NVARCHAR(20),
	NGAYSINH DATE,
	CMND CHAR(15),
	SDT CHAR(10),
	EMAIL VARCHAR(25),
	DIACHI NVARCHAR(50),
	VITRI NVARCHAR(20),
	LUONG FLOAT,
	VAITRO NVARCHAR(20),
	TRUNGTAM INT,
	SOBUOITRUCTOITHIEU INT,
	PRIMARY KEY (MANV)
);

CREATE TABLE TRUNGTAM (
	STT INT,
	DIACHI NVARCHAR(50),
	NGAYBATDAU DATE,
	PRIMARY KEY (STT)
);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_TRUNGTAM_NHANVIEN FOREIGN KEY (TRUNGTAM) REFERENCES TRUNGTAM(STT);

CREATE TABLE BANGCAP(
	MANV INT NOT NULL,
	MABANGCAP INT NOT NULL,
	TENBANG NVARCHAR(20),
	NOICAP NVARCHAR(20),
	CAPBAC NVARCHAR(20),
	LINHVUC NVARCHAR(20)
);

ALTER TABLE BANGCAP
ADD CONSTRAINT FK_NHANVIEN_BANGCAP FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE BANGCAP
ADD CONSTRAINT PK_BANGCAP PRIMARY KEY (MANV, MABANGCAP);


CREATE TABLE LICHLAMVIEC(
	MANV INT NOT NULL,
	MALICHLV INT NOT NULL,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	THOIGIANTAO DATETIME
);

ALTER TABLE LICHLAMVIEC
ADD CONSTRAINT FK_NHANVIEN_LICHLAMVIEC FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE LICHLAMVIEC
ADD CONSTRAINT PK_LICHLAMVIEC PRIMARY KEY (MANV, MALICHLV)


CREATE TABLE LICHCATRUC(
	MANV INT NOT NULL,
	MALICHLV INT NOT NULL,
	NGAY DATE,
	THU NVARCHAR(10),
	BUOI NVARCHAR(6),
);

ALTER TABLE LICHCATRUC
ADD CONSTRAINT FK_LICHLAMVIEC_LICHCATRUC FOREIGN KEY (MANV, MALICHLV) REFERENCES LICHLAMVIEC(MANV, MALICHLV);



CREATE TABLE LICHRANH(
	MANV INT NOT NULL,
	MALICHRANH INT NOT NULL, --ADDED TO USE CHITIETLICHRANH
	THOIGIANDANGKY DATETIME,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	SOBUOIRANH INT,

);

ALTER TABLE LICHRANH
ADD CONSTRAINT FK_NHANVIEN_LICHRANH FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE LICHRANH
ADD CONSTRAINT PK_LICHRANH PRIMARY KEY (MANV, MALICHRANH);
CREATE TABLE CHITIETLICHRANH(
	MANV INT,
	MALICHRANH INT,
	THU NVARCHAR(8),
	NGAY DATE,
	CA NVARCHAR(6),
	TRANGTHAI NVARCHAR(20)

);

ALTER TABLE CHITIETLICHRANH
ADD CONSTRAINT FK_LICHRANH_CHITIET FOREIGN KEY (MANV, MALICHRANH) REFERENCES LICHRANH(MANV, MALICHRANH)


--KHACHHANG

CREATE TABLE KHACHHANG(
	MAKH INT,
	HOVATEN NVARCHAR(20),
	GIOITINH NVARCHAR(3),
	DIACHI NVARCHAR(50),
	SDT CHAR(10),
	NGAYSINH DATE,
	PRIMARY KEY (MAKH)
);

CREATE TABLE TREEM(
	MAKH INT,
	NGUOIGIAMHO VARCHAR(20),
	MQH VARCHAR(10),
	SDTGIAMHO CHAR(10)
);

ALTER TABLE TREEM
ADD CONSTRAINT FK_KHACHHANG_TREEM FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

CREATE TABLE VACCINE(
	MAVACCINE INT,
	TENVACCINE NVARCHAR(15),
	SOLUONG INT,
	PRIMARY KEY (MAVACCINE)
);

CREATE TABLE LOVACCINE(
	MALO INT,
	MAVACCINE INT,
	NGAYNHAP DATE,
	SOLIEUCONLAI INT,
	HANSUDUNG DATE,
	PRIMARY KEY (MALO)
);

ALTER TABLE LOVACCINE
ADD CONSTRAINT FK_VACCINE_LOVACCINE FOREIGN KEY (MAVACCINE) REFERENCES VACCINE(MAVACCINE);

CREATE TABLE PHIEUDKTIEM(
	MAKH INT NOT NULL,
	MAPHIEU INT NOT NULL,
	GOI NVARCHAR(10),
	NGAYTIEM DATE,
	TINHTRANG NVARCHAR(10)
)

ALTER TABLE PHIEUDKTIEM
ADD CONSTRAINT FK_KHACHHANG_PHIEUDK FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);
ALTER TABLE PHIEUDKTIEM
ADD CONSTRAINT PK_PHIEUDKTIEM PRIMARY KEY (MAKH,MAPHIEU)
CREATE TABLE TIEMLE(
	MAKH INT,
	MAPHIEU INT,
	THOIGIANTIEM DATETIME,
	MAVACCINE INT
)
ALTER TABLE TIEMLE 
ADD CONSTRAINT FK_PHIEUDK_TIEMLE FOREIGN KEY (MAKH, MAPHIEU) REFERENCES PHIEUDKTIEM(MAKH, MAPHIEU)

CREATE TABLE HOADON(
	MAHD INT,
	HINHTHUCTHANHTOAN NVARCHAR(15),
	THANHTIEN FLOAT,
	THOIGIANTHANHTOAN DATETIME, --THOI GIAN HAY THOI DIEM?
	MAKH INT,
	MAPHIEU INT,
	PRIMARY KEY (MAHD)
);

ALTER TABLE HOADON
ADD CONSTRAINT FK_PHIEUDK_HOADON FOREIGN KEY (MAKH,MAPHIEU) REFERENCES PHIEUDKTIEM(MAKH, MAPHIEU);




CREATE TABLE PHIEUNHAPHANG(
	MAPHIEU INT NOT NULL,
	MAVACCINE INT,
	NHACUNGCAP NVARCHAR(15),
	SOLUONG INT,
	PRIMARY KEY (MAPHIEU)
);

ALTER TABLE PHIEUNHAPHANG
ADD CONSTRAINT FK_VACCINE_PHIEUNHAPHANG FOREIGN KEY (MAVACCINE) REFERENCES VACCINE(MAVACCINE);

CREATE TABLE PHIEUDATMUA(
	MAPHIEUMUA INT,
	MAVACCINE INT,
	PRIMARY KEY (MAPHIEUMUA)
);
ALTER TABLE PHIEUDATMUA
ADD CONSTRAINT FK_VACCINE_PHIEUDATMUA FOREIGN KEY (MAVACCINE) REFERENCES VACCINE(MAVACCINE);

CREATE TABLE BAOCAOTIEMNGUA(
	MAKH INT NOT NULL,
	STT INT NOT NULL,
	NGAYTIEM DATE,
	MAVACCINE INT,
	MALO INT,
	TRIEUCHUNG NVARCHAR(100)
);

ALTER TABLE BAOCAOTIEMNGUA
ADD CONSTRAINT FK_KHACHHANG_BAOCAO FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH);

ALTER TABLE BAOCAOTIEMNGUA
ADD CONSTRAINT FK_VACCINE_BAOCAO FOREIGN KEY (MAVACCINE) REFERENCES VACCINE(MAVACCINE);

ALTER TABLE BAOCAOTIEMNGUA
ADD CONSTRAINT FK_LOVACCINE_BAOCAO FOREIGN KEY (MALO) REFERENCES LOVACCINE(MALO);

--ALTER TABLE BAOCAOTIEMNGUA
--ADD CONSTRAINT PK_BAOCAO PRIMARY KEY (MAKH, STT) 
--need help on this constraint :(

